### ISSUE TITLE
not working for Meteor 1.2.0.1.

### ISSUE THREAD

**Issue by onsombal** [particle4dev/upload-avatar-meteor#5]
Below is the error returned after upgrading to Meteor 1.2.0.1.

While building package upload-avatar:
error: No plugin known to handle file
'src/vendor/imgareaselect/border-anim-h.gif'. If you want this file to be a
static asset, use addAssets instead of addFiles; eg,
api.addAssets('src/vendor/imgareaselect/border-anim-h.gif', 'client').
error: No plugin known to handle file
'src/vendor/imgareaselect/border-anim-v.gif'. If you want this file to be a
static asset, use addAssets instead of addFiles; eg,
api.addAssets('src/vendor/imgareaselect/border-anim-v.gif', 'client').

**Comment by CloneXpert** [comment]
+1

**Comment by selaias** [comment]
created a pull request fix all issues.

**Comment by particle4dev** [comment]
Hi guys,
I am not work with meteor on my new job, so i don't have time to maintain this package any longer (im still huge fan of meteor). Please let me know if you guy want to maintain this package. I will add you as a contributor and feel free to added your name as author.
Leave your email and meteor accout below !

Best,
Hoang
